// Generated by db9 gen types

export interface Artifacts {
  id: number;
  task_id: number | null;
  agent: string;
  kind: string;
  path: string | null;
  content: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string | null;
}

export interface Hypotheses {
  id: number;
  parent_id: number | null;
  agent: string;
  title: string;
  rationale: string | null;
  expected_value: string | null;
  estimated_cost: string | null;
  status: string;
  outcome: string | null;
  evidence_artifact_ids: unknown | null;
  created_at: string | null;
  resolved_at: string | null;
}

export interface LoopEvents {
  id: number;
  run_id: string;
  loop_number: number;
  event_type: string;
  classification: string | null;
  agent: string | null;
  payload: Record<string, unknown>;
  created_at: string | null;
}

export interface Memory {
  id: number;
  agent: string;
  scope: string;
  kind: string;
  content: string;
  embedding: unknown | null;
  created_at: string | null;
  superseded_by: number | null;
}

export interface RunFeedback {
  id: number;
  run_id: string | null;
  agent: string;
  skill_version: string | null;
  task_completed: boolean | null;
  cost_usd: number | null;
  duration_ms: number | null;
  token_count: number | null;
  errored: boolean | null;
  human_intervention: boolean | null;
  steer_count: number | null;
  loop_number: number | null;
  created_at: string | null;
}

export interface Runs {
  id: string;
  goal: string | null;
  config: Record<string, unknown> | null;
  started_at: string | null;
  ended_at: string | null;
  total_loops: number | null;
  productive_loops: number | null;
  total_tokens: number | null;
  total_cost_usd: number | null;
  exit_reason: string | null;
  metadata: Record<string, unknown> | null;
}

export interface SkillEvals {
  id: number;
  agent: string;
  eval_name: string;
  skill_version: string;
  pass_rate: number | null;
  avg_tokens: number | null;
  avg_duration_ms: number | null;
  model: string | null;
  created_at: string | null;
}

export interface Tasks {
  id: number;
  title: string;
  status: string | null;
  claimed_by: string | null;
  claimed_at: string | null;
  depends_on: unknown | null;
  result: Record<string, unknown> | null;
  created_at: string | null;
}

