// Type declaration for the auto-generated embedded-assets module.
// The actual module is generated by build-standalone.mjs and only exists during standalone builds.
export declare const ENTRYPOINT_JS: string
export declare const CLI_JS: string
export declare const AGENT_CONFIGS: Record<string, string>
export declare const AGENT_SKILLS: Record<string, string>
export declare const SHARED_SKILLS: Record<string, string>
export declare const PRODUCTS_JSON: string | null
